#!/bin/bash -l

sh code/ms_simulate_haplotypes_local.sh 1 norm sim003
sh code/ms_simulate_haplotypes_local.sh 4 norm sim003
sh code/ms_simulate_haplotypes_local.sh 7 norm sim003
sh code/ms_simulate_haplotypes_local.sh 10 norm sim003
sh code/ms_simulate_haplotypes_local.sh 13 norm sim003
sh code/ms_simulate_haplotypes_local.sh 16 norm sim003
sh code/ms_simulate_haplotypes_local.sh 19 norm sim003
sh code/ms_simulate_haplotypes_local.sh 22 norm sim003
sh code/ms_simulate_haplotypes_local.sh 25 norm sim003
sh code/ms_simulate_haplotypes_local.sh 1 unif sim003
sh code/ms_simulate_haplotypes_local.sh 4 unif sim003
sh code/ms_simulate_haplotypes_local.sh 7 unif sim003
sh code/ms_simulate_haplotypes_local.sh 10 unif sim003
sh code/ms_simulate_haplotypes_local.sh 13 unif sim003
sh code/ms_simulate_haplotypes_local.sh 16 unif sim003
sh code/ms_simulate_haplotypes_local.sh 19 unif sim003
sh code/ms_simulate_haplotypes_local.sh 22 unif sim003
sh code/ms_simulate_haplotypes_local.sh 25 unif sim003
sh code/ms_simulate_haplotypes_local.sh 1 gamma sim003
sh code/ms_simulate_haplotypes_local.sh 4 gamma sim003
sh code/ms_simulate_haplotypes_local.sh 7 gamma sim003
sh code/ms_simulate_haplotypes_local.sh 10 gamma sim003
sh code/ms_simulate_haplotypes_local.sh 13 gamma sim003
sh code/ms_simulate_haplotypes_local.sh 16 gamma sim003
sh code/ms_simulate_haplotypes_local.sh 19 gamma sim003
sh code/ms_simulate_haplotypes_local.sh 22 gamma sim003
sh code/ms_simulate_haplotypes_local.sh 25 gamma sim003
sh code/ms_simulate_haplotypes_local.sh 1 beta sim003
sh code/ms_simulate_haplotypes_local.sh 4 beta sim003
sh code/ms_simulate_haplotypes_local.sh 7 beta sim003
sh code/ms_simulate_haplotypes_local.sh 10 beta sim003
sh code/ms_simulate_haplotypes_local.sh 13 beta sim003
sh code/ms_simulate_haplotypes_local.sh 16 beta sim003
sh code/ms_simulate_haplotypes_local.sh 19 beta sim003
sh code/ms_simulate_haplotypes_local.sh 22 beta sim003
sh code/ms_simulate_haplotypes_local.sh 25 beta sim003
